# The following redirect is intended for use with most SPAs that handle
# routing internally.

[build]
  base = "/"
  publish = "public"
  command = "npm run build"
  functions = "lambda/build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200